export const footer21 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "" },
  { key: "totalTraffic" },
  { key: "totalRevenue" },
];

export const createFooter25 = () => {
  const defaultKey = [
    "totalMinute00",
    "totalMinute05",
    "totalMinute10",
    "totalMinute15",
    "totalMinute20",
    "totalMinute25",
    "totalMinute30",
    "totalMinute35",
    "totalMinute40",
    "totalMinute45",
    "totalMinute50",
    "totalMinute55",
    "totalMinuteTotal",
  ];
  let result = [{ key: "รวม" }, { key: "รวม" }];
  for (let i = 0; i < 24; i++) {
    defaultKey.forEach((item, index) => {
      result.push({ key: `${i}${item}`, type: "nullColumn" });
    });
  }
  return result;
};

export const footer26 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficHourly00" },
  { key: "totalTrafficHourly01" },
  { key: "totalTrafficHourly02" },
  { key: "totalTrafficHourly03" },
  { key: "totalTrafficHourly04" },
  { key: "totalTrafficHourly05" },
  { key: "totalTrafficHourly06" },
  { key: "totalTrafficHourly07" },
  { key: "totalTrafficHourly08" },
  { key: "totalTrafficHourly09" },
  { key: "totalTrafficHourly10" },
  { key: "totalTrafficHourly11" },
  { key: "totalTrafficHourly12" },
  { key: "totalTrafficHourly13" },
  { key: "totalTrafficHourly14" },
  { key: "totalTrafficHourly15" },
  { key: "totalTrafficHourly16" },
  { key: "totalTrafficHourly17" },
  { key: "totalTrafficHourly18" },
  { key: "totalTrafficHourly19" },
  { key: "totalTrafficHourly20" },
  { key: "totalTrafficHourly21" },
  { key: "totalTrafficHourly22" },
  { key: "totalTrafficHourly23" },
  { key: "totalTrafficHourlyTotal" },
];

export const footer28 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficMonthly01" },
  { key: "totalRevenueMonthly01" },
  { key: "totalTrafficMonthly02" },
  { key: "totalRevenueMonthly02" },
  { key: "totalTrafficMonthly03" },
  { key: "totalRevenueMonthly03" },
  { key: "totalTrafficMonthly04" },
  { key: "totalRevenueMonthly04" },
  { key: "totalTrafficMonthly05" },
  { key: "totalRevenueMonthly05" },
  { key: "totalTrafficMonthly06" },
  { key: "totalRevenueMonthly06" },
  { key: "totalTrafficMonthly07" },
  { key: "totalRevenueMonthly07" },
  { key: "totalTrafficMonthly08" },
  { key: "totalRevenueMonthly08" },
  { key: "totalTrafficMonthly09" },
  { key: "totalRevenueMonthly09" },
  { key: "totalTrafficMonthly10" },
  { key: "totalRevenueMonthly10" },
  { key: "totalTrafficMonthly11" },
  { key: "totalRevenueMonthly11" },
  { key: "totalTrafficMonthly12" },
  { key: "totalRevenueMonthly12" },
  { key: "totalTrafficMonthlyTotal" },
  { key: "totalRevenueMonthlyTotal" },
];

export const footer211 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficExemMonthly01" },
  { key: "totalTrafficLeftXMonthly01" },
  { key: "totalTrafficHpmcMonthly01" },
  { key: "totalTrafficExemMonthly02" },
  { key: "totalTrafficLeftXMonthly02" },
  { key: "totalTrafficHpmcMonthly02" },
  { key: "totalTrafficExemMonthly03" },
  { key: "totalTrafficLeftXMonthly03" },
  { key: "totalTrafficHpmcMonthly03" },
  { key: "totalTrafficExemMonthly04" },
  { key: "totalTrafficLeftXMonthly04" },
  { key: "totalTrafficHpmcMonthly04" },
  { key: "totalTrafficExemMonthly05" },
  { key: "totalTrafficLeftXMonthly05" },
  { key: "totalTrafficHpmcMonthly05" },
  { key: "totalTrafficExemMonthly06" },
  { key: "totalTrafficLeftXMonthly06" },
  { key: "totalTrafficHpmcMonthly06" },
  { key: "totalTrafficExemMonthly07" },
  { key: "totalTrafficLeftXMonthly07" },
  { key: "totalTrafficHpmcMonthly07" },
  { key: "totalTrafficExemMonthly08" },
  { key: "totalTrafficLeftXMonthly08" },
  { key: "totalTrafficHpmcMonthly08" },
  { key: "totalTrafficExemMonthly09" },
  { key: "totalTrafficLeftXMonthly09" },
  { key: "totalTrafficHpmcMonthly09" },
  { key: "totalTrafficExemMonthly10" },
  { key: "totalTrafficLeftXMonthly10" },
  { key: "totalTrafficHpmcMonthly10" },
  { key: "totalTrafficExemMonthly11" },
  { key: "totalTrafficLeftXMonthly11" },
  { key: "totalTrafficHpmcMonthly11" },
  { key: "totalTrafficExemMonthly12" },
  { key: "totalTrafficLeftXMonthly12" },
  { key: "totalTrafficHpmcMonthly12" },
  { key: "totalTrafficExemMonthlyTotal" },
  { key: "totalTrafficLeftXMonthlyTotal" },
  { key: "totalTrafficHpmcMonthlyTotal" },
];

export const footer213 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "trafficJanuaryTotal" },
  { key: "trafficFebruaryTotal" },
  { key: "trafficMarchTotal" },
  { key: "trafficAprilTotal" },
  { key: "trafficMayTotal" },
  { key: "trafficJuneTotal" },
  { key: "trafficJulyTotal" },
  { key: "trafficAugustTotal" },
  { key: "trafficSeptemberTotal" },
  { key: "trafficOctoberTotal" },
  { key: "trafficNovemberTotal" },
  { key: "trafficDecemberTotal" },
  { key: "trafficTotalTotal" },
];

export const footer214 = [
  { key: "รวม" },
  { key: "totalTrxShiftA" },
  { key: "totalTrxShiftB" },
  { key: "totalTrxShiftC" },
  { key: "totalTrxTotal" },
];
export const footer215 = [
  { key: "รวม" },
  { key: "totalTraffic" },
  { key: "totalPercent" },
];

export const footer31 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer32 = [
  /*5*/ { key: "" },
  /*1*/ { key: "รวม" },
  /*2*/ { key: "รวม" },
  /*3*/ { key: "count" },
  /*4*/ { key: "rows" },

  /*6*/ { key: "" },
  /*7*/ { key: "" },
  /*8*/ { key: "" },
  /*9*/ { key: "" },
  /*10*/ { key: "" },
  /*11*/ { key: "" },
  /*12*/ { key: "" },
  /*13*/ { key: "" },
  /*14*/ { key: "" },
  /*15*/ { key: "" },
  /*16*/ { key: "" },
  /*17*/ { key: "" },
  /*18*/ { key: "" },
  /*19*/ { key: "" },
  /*19*/ { key: "" },
  /*19*/ { key: "" },
  /*19*/ { key: "" },
  // { key: "" },
];

export const footer33 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalabnormalWrongType" },
  { key: "totalabnormalViolation" },
  { key: "totalabnormalExem" },
  { key: "totalabnormalLeftExit" },
  { key: "totalabnormalTotal" },
  { key: "totaldisAvc" },
  { key: "totaldisTc" },
  { key: "totaluapMoney" },
  { key: "totaluapNonMoney" },
  { key: "totalexemQualify" },
  { key: "totalexemNonQualify" },
  { key: "totalleftExitQualify" },
  { key: "totalleftExitNonQualify" },
  { key: "totalnonAdjust" },
];

export const footer33_sub = [
  /*5*/ { key: "" },
  /*1*/ { key: "รวม" },
  /*2*/ { key: "รวม" },
  /*3*/ { key: "count" },
  /*4*/ { key: "rows" },
  /*6*/ { key: "" },
  /*7*/ { key: "" },
  /*8*/ { key: "" },
  /*9*/ { key: "" },
  /*10*/ { key: "" },
  /*11*/ { key: "" },
  /*12*/ { key: "" },
  /*13*/ { key: "" },
  /*14*/ { key: "" },
  /*15*/ { key: "" },
  /*16*/ { key: "" },
  /*17*/ { key: "" },
  /*18*/ { key: "" },
  /*19*/ { key: "" },
  /*20*/ { key: "" },
  /*20*/ { key: "" },
  /*20*/ { key: "" },
];
export const footer34 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "totalAmountBth" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];
export const footer35 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer36 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer37 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer311 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer41 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficHourly00" },
  { key: "totalRevenueHourly00" },
  { key: "totalTrafficHourly01" },
  { key: "totalRevenueHourly01" },
  { key: "totalTrafficHourly02" },
  { key: "totalRevenueHourly02" },
  { key: "totalTrafficHourly03" },
  { key: "totalRevenueHourly03" },
  { key: "totalTrafficHourly04" },
  { key: "totalRevenueHourly04" },
  { key: "totalTrafficHourly05" },
  { key: "totalRevenueHourly05" },
  { key: "totalTrafficHourly06" },
  { key: "totalRevenueHourly06" },
  { key: "totalTrafficHourly07" },
  { key: "totalRevenueHourly07" },
  { key: "totalTrafficHourly08" },
  { key: "totalRevenueHourly08" },
  { key: "totalTrafficHourly09" },
  { key: "totalRevenueHourly09" },
  { key: "totalTrafficHourly10" },
  { key: "totalRevenueHourly10" },
  { key: "totalTrafficHourly11" },
  { key: "totalRevenueHourly11" },
  { key: "totalTrafficHourly12" },
  { key: "totalRevenueHourly12" },
  { key: "totalTrafficHourly13" },
  { key: "totalRevenueHourly13" },
  { key: "totalTrafficHourly14" },
  { key: "totalRevenueHourly14" },
  { key: "totalTrafficHourly15" },
  { key: "totalRevenueHourly15" },
  { key: "totalTrafficHourly16" },
  { key: "totalRevenueHourly16" },
  { key: "totalTrafficHourly17" },
  { key: "totalRevenueHourly17" },
  { key: "totalTrafficHourly18" },
  { key: "totalRevenueHourly18" },
  { key: "totalTrafficHourly19" },
  { key: "totalRevenueHourly19" },
  { key: "totalTrafficHourly20" },
  { key: "totalRevenueHourly20" },
  { key: "totalTrafficHourly21" },
  { key: "totalRevenueHourly21" },
  { key: "totalTrafficHourly22" },
  { key: "totalRevenueHourly22" },
  { key: "totalTrafficHourly23" },
  { key: "totalRevenueHourly23" },
  { key: "totalTrafficHourlyTotal" },
  { key: "totalRevenueHourlyTotal" },
];

export const footer43 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficMonthly01" },
  { key: "totalRevenueMonthly01" },
  { key: "totalTrafficMonthly02" },
  { key: "totalRevenueMonthly02" },
  { key: "totalTrafficMonthly03" },
  { key: "totalRevenueMonthly03" },
  { key: "totalTrafficMonthly04" },
  { key: "totalRevenueMonthly04" },
  { key: "totalTrafficMonthly05" },
  { key: "totalRevenueMonthly05" },
  { key: "totalTrafficMonthly06" },
  { key: "totalRevenueMonthly06" },
  { key: "totalTrafficMonthly07" },
  { key: "totalRevenueMonthly07" },
  { key: "totalTrafficMonthly08" },
  { key: "totalRevenueMonthly08" },
  { key: "totalTrafficMonthly09" },
  { key: "totalRevenueMonthly09" },
  { key: "totalTrafficMonthly10" },
  { key: "totalRevenueMonthly10" },
  { key: "totalTrafficMonthly11" },
  { key: "totalRevenueMonthly11" },
  { key: "totalTrafficMonthly12" },
  { key: "totalRevenueMonthly12" },
  { key: "totalTrafficMonthlyTotal" },
  { key: "totalRevenueMonthlyTotal" },
];

export const footer44 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficHourly00" },
  { key: "totalRevenueHourly00" },
  { key: "totalTrafficHourly01" },
  { key: "totalRevenueHourly01" },
  { key: "totalTrafficHourly02" },
  { key: "totalRevenueHourly02" },
  { key: "totalTrafficHourly03" },
  { key: "totalRevenueHourly03" },
  { key: "totalTrafficHourly04" },
  { key: "totalRevenueHourly04" },
  { key: "totalTrafficHourly05" },
  { key: "totalRevenueHourly05" },
  { key: "totalTrafficHourly06" },
  { key: "totalRevenueHourly06" },
  { key: "totalTrafficHourly07" },
  { key: "totalRevenueHourly07" },
  { key: "totalTrafficHourly08" },
  { key: "totalRevenueHourly08" },
  { key: "totalTrafficHourly09" },
  { key: "totalRevenueHourly09" },
  { key: "totalTrafficHourly10" },
  { key: "totalRevenueHourly10" },
  { key: "totalTrafficHourly11" },
  { key: "totalRevenueHourly11" },
  { key: "totalTrafficHourly12" },
  { key: "totalRevenueHourly12" },
  { key: "totalTrafficHourly13" },
  { key: "totalRevenueHourly13" },
  { key: "totalTrafficHourly14" },
  { key: "totalRevenueHourly14" },
  { key: "totalTrafficHourly15" },
  { key: "totalRevenueHourly15" },
  { key: "totalTrafficHourly16" },
  { key: "totalRevenueHourly16" },
  { key: "totalTrafficHourly17" },
  { key: "totalRevenueHourly17" },
  { key: "totalTrafficHourly18" },
  { key: "totalRevenueHourly18" },
  { key: "totalTrafficHourly19" },
  { key: "totalRevenueHourly19" },
  { key: "totalTrafficHourly20" },
  { key: "totalRevenueHourly20" },
  { key: "totalTrafficHourly21" },
  { key: "totalRevenueHourly21" },
  { key: "totalTrafficHourly22" },
  { key: "totalRevenueHourly22" },
  { key: "totalTrafficHourly23" },
  { key: "totalRevenueHourly23" },
  { key: "totalTrafficHourlyTotal" },
  { key: "totalRevenueHourlyTotal" },
];

export const footer45 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTraffic" },
  { key: "totalRevenue" },
];

export const footer46 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "totalTrafficMonthly01" },
  { key: "totalRevenueMonthly01" },
  { key: "totalTrafficMonthly02" },
  { key: "totalRevenueMonthly02" },
  { key: "totalTrafficMonthly03" },
  { key: "totalRevenueMonthly03" },
  { key: "totalTrafficMonthly04" },
  { key: "totalRevenueMonthly04" },
  { key: "totalTrafficMonthly05" },
  { key: "totalRevenueMonthly05" },
  { key: "totalTrafficMonthly06" },
  { key: "totalRevenueMonthly06" },
  { key: "totalTrafficMonthly07" },
  { key: "totalRevenueMonthly07" },
  { key: "totalTrafficMonthly08" },
  { key: "totalRevenueMonthly08" },
  { key: "totalTrafficMonthly09" },
  { key: "totalRevenueMonthly09" },
  { key: "totalTrafficMonthly10" },
  { key: "totalRevenueMonthly10" },
  { key: "totalTrafficMonthly11" },
  { key: "totalRevenueMonthly11" },
  { key: "totalTrafficMonthly12" },
  { key: "totalRevenueMonthly12" },
  { key: "totalTrafficMonthlyTotal" },
  { key: "totalRevenueMonthlyTotal" },
];

export const footer48 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "mtcTrafficCashTotal" },
  { key: "mtcRevenueCashTotal" },
  { key: "mtcTrafficCouponTotal" },
  { key: "mtcRevenueCouponTotal" },
  { key: "mtcTrafficEmvTotal" },
  { key: "mtcRevenueEmvTotal" },
  { key: "mtcTrafficQrTotal" },
  { key: "mtcRevenueQrTotal" },
  { key: "easypassTrafficTotal" },
  { key: "easypassRevenueTotal" },
  { key: "mpassTrafficTotal" },
  { key: "mpassRevenueTotal" },
  { key: "mtcTrafficTotalTotal" },
  { key: "mtcRevenueTotalTotal" },
  { key: "etcTrafficTotalTotal" },
  { key: "etcRevenueTotalTotal" },
  { key: "trafficTotalTotal" },
  { key: "revenueTotalTotal" },
];

export const footer49 = [
  { key: "รวม" },
  { key: "mtcTrafficCashTotal" },
  { key: "mtcRevenueCashTotal" },
  { key: "mtcTrafficCouponTotal" },
  { key: "mtcRevenueCouponTotal" },
  { key: "mtcTrafficEmvTotal" },
  { key: "mtcRevenueEmvTotal" },
  { key: "mtcTrafficQrTotal" },
  { key: "mtcRevenueQrTotal" },
  { key: "easypassTrafficTotal" },
  { key: "easypassRevenueTotal" },
  { key: "mpassTrafficTotal" },
  { key: "mpassRevenueTotal" },
  { key: "mtcTrafficTotalTotal" },
  { key: "mtcRevenueTotalTotal" },
  { key: "etcTrafficTotalTotal" },
  { key: "etcRevenueTotalTotal" },
  { key: "trafficTotalTotal" },
  { key: "revenueTotalTotal" },
];

export const footer57 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "tollTotalTotal" },
  { key: "class1Diss0Total" },
  { key: "class1Diss2Total" },
  { key: "class1Diss5Total" },
  { key: "class1Diss255Total" },
  { key: "class2Diss0Total" },
  { key: "class2Diss2Total" },
  { key: "class2Diss5Total" },
  { key: "class2Diss255Total" },
  { key: "summaryErrorTotal" },
  { key: "percentAverage" },
];

export const footer66 = [
  { key: "totalDescTh" },
  { key: "totalDescTh" },
  { key: "totalSupAdjust" },
  { key: "totalTodSod" },
  { key: "totalMccTod" },
  { key: "totalMccSod" },
  { key: "totalNumberTod" },
  { key: "averagePercentAudit" },
];

export const footer62 = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountFromShipping" },
  { key: "totalAmountFromSystem" },
  { key: "totalAmountDiff" },
  { key: "totalAmountFromShippingCoupon" },
  { key: "totalAmountFromSystemCoupon" },
  { key: "totalAmountDiffCoupon" },
  { key: "totalAmountNoVatCoupon" },
  { key: "totalAmountQrKbankBank" },
  { key: "totalAmountQrKbankSod" },
  { key: "totalAmountQrKbankDiff" },
  { key: "totalAmountQrKtbBank" },
  { key: "totalAmountQrKtbSod" },
  { key: "totalAmountQrKtbDiff" },
  { key: "totalAmountEmvKtbBank" },
  { key: "totalAmountEmvKtbSod" },
  { key: "totalAmountEmvKtbDiff" },
];

export const footer62Detail = [];

export const footer67 = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountFromShipping" },
  { key: "totalAmountCashSap" },
  { key: "totalAmountFromSystem" },
  { key: "totalAmountDiff" },
  { key: "totalCountMccCoupon30" },
  { key: "totalAmountFromSystemCoupon" },
  { key: "totalAmountDiffCoupon" },
  { key: "totalAmountQrBank" },
  { key: "totalAmountQrSod" },
  { key: "totalAmountQrDiff" },
];

export const footer67A = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountFromShipping" },
  { key: "totalAmountCashSap" },
  { key: "totalAmountFromSystem" },
  { key: "totalAmountDiff" },
  { key: "totalCountMccCoupon30" },
  { key: "totalAmountFromSystemCoupon" },
  { key: "totalAmountDiffCoupon" },
];

export const footer67B = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountQrBank" },
  { key: "totalAmountQrSod" },
  { key: "totalAmountQrDiff" },
];

export const footer67C = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountEmvBank" },
  { key: "totalAmountEmvSod" },
  { key: "totalAmountEmvDiff" },
];

export const footer67D = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountMpassBank" },
  { key: "totalAmountMpassSod" },
  { key: "totalAmountMpassDiff" },
];

export const footer67E = [
  { key: "รวมทั้งหมด" },
  { key: "รวมทั้งหมด" },
  { key: "totalAmountEasyPassBank" },
  { key: "totalAmountEasyPassSod" },
  { key: "totalAmountEasyPassDiff" },
];

export const footer611 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer612 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "totalCash" },
  { key: "totalCoupon" },
  { key: "totalQr" },
  { key: "totalTotal" },
];

export const footer620 = [
  { key: "order" },
  { key: "saveDate" },
  { key: "trxDate" },
  { key: "typeText" },
  { key: "trxEasypass" },
  { key: "amountEasypass" },
  { key: "trxOverdueEasypass" },
  { key: "amountOverdueEasypass" },
  { key: "trxMpass" },
  { key: "amountMpass" },
  { key: "trxOverdueMpass" },
  { key: "amountOverdueMpass" },
];

export const footer71 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "totalAmountSum" },
  { key: "totalDeclareAmount" },
  { key: "totalDifferentAmount" },
  { key: "allTotal" },
];


export const footer77 = [
  { key: "รวม" },
  { key: "amTotal" },
  { key: "pmTotal" },
  { key: "nightTotal" },
  { key: "tollTotal" },
  { key: "tollPercent" },
];

export const footer64 = [
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "amountTotalDmt" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "amountTotalBank" },
  { key: "" },
  { key: "" },
];

export const footer84 = [
  { key: "" },
  { key: "รวม" },
  { key: "รวม" },
  { key: "count" },
  { key: "rows" },
  { key: "" },
  { key: "totalAmountBth" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];

export const footer93 = [
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
  { key: "" },
];